'use strict';

function pad(s, n) { s = String(s); return s + ' '.repeat(Math.max(0, n - s.length)); }
function dollar(n) { return n == null ? '?' : '$' + n.toFixed(n < 1 ? 4 : 2); }

function renderText(workflows, projection, opts) {
  const lines = [];
  lines.push(`gha-budget  ${new Date().toISOString()}`);
  lines.push('');
  lines.push(`Assumed: ${opts.minutes} min/job, ${projection.runsPerDay} runs/day.`);
  lines.push('');
  for (const wf of workflows) {
    if (wf.error) {
      lines.push(`${wf.filename}  ERROR  ${wf.error}`);
      continue;
    }
    lines.push(wf.filename);
    lines.push(`  ${pad('job', 22)}${pad('runs-on', 22)}${pad('matrix', 8)}${pad('min/run', 9)}${pad('rate/min', 11)}per-run`);
    for (const j of wf.jobs) {
      lines.push(
        '  ' +
        pad(j.job, 22) +
        pad(j.runsOn, 22) +
        pad(j.matrix.toString(), 8) +
        pad(j.minutesPerRun.toString(), 9) +
        pad(j.ratePerMinUsd == null ? '?' : '$' + j.ratePerMinUsd.toFixed(3), 11) +
        (j.costPerRunUsd == null ? (j.selfHosted ? '$0.00 (self-hosted)' : '?') : dollar(j.costPerRunUsd))
      );
    }
    lines.push(`  -> workflow per-run: ${dollar(wf.totalCostPerRunUsd)}`);
    lines.push('');
  }
  lines.push(`All workflows per-run total: ${dollar(projection.totalPerRunUsd)}`);
  lines.push(`Daily   (${projection.runsPerDay} runs/day): ${dollar(projection.dailyUsd)}`);
  lines.push(`Monthly (30 days):           ${dollar(projection.monthlyUsd)}`);
  lines.push('');
  lines.push('tips:');
  lines.push('  --runs-per-day=20    your team push + PR frequency');
  lines.push('  --minutes=5          mean runtime per job');
  lines.push('  --json               machine-readable for CI');
  lines.push('');
  lines.push('Free CLIs: ci-doctor (audit), depmedic (npm vulns), cursor-rules-init (.cursorrules).');
  return lines.join('\n');
}

function renderJson(workflows, projection, opts) {
  return JSON.stringify({
    generatedAt: new Date().toISOString(),
    assumptions: { minutesPerJob: opts.minutes, runsPerDay: projection.runsPerDay },
    workflows,
    projection,
  }, null, 2);
}

function renderMarkdown(workflows, projection, opts) {
  const lines = [];
  lines.push('### gha-budget report');
  lines.push('');
  lines.push(`**Total per run**: ${dollar(projection.totalPerRunUsd)}  ` +
    `**Daily** (${projection.runsPerDay}/day): ${dollar(projection.dailyUsd)}  ` +
    `**Monthly**: ${dollar(projection.monthlyUsd)}`);
  lines.push('');
  lines.push(`Assumed ${opts.minutes} min/job. Override with \`--minutes=N --runs-per-day=N\`.`);
  lines.push('');
  lines.push('| File | Job | Runs-on | Matrix | Min/run | Per-run |');
  lines.push('| - | - | - | - | - | - |');
  for (const wf of workflows) {
    if (wf.error) {
      lines.push(`| \`${wf.filename}\` | ERROR | - | - | - | ${wf.error} |`);
      continue;
    }
    for (const j of wf.jobs) {
      const cost = j.selfHosted ? '$0.00 (self-hosted)' : dollar(j.costPerRunUsd);
      lines.push(`| \`${wf.filename}\` | \`${j.job}\` | \`${j.runsOn}\` | ${j.matrix} | ${j.minutesPerRun} | ${cost} |`);
    }
  }
  lines.push('');
  lines.push('_generated by [gha-budget](https://github.com/depmedicdev-byte/gha-budget). The full pattern set for cutting these numbers is in the [GHA cost cookbook](https://buy.polar.sh/polar_cl_E2HGFeAVxJ64gU0Tv0qGwAueuxvhuq6A0pjhE4BWTyD)._');
  return lines.join('\n');
}

module.exports = { renderText, renderJson, renderMarkdown };
